name: LinAlg2
channels:
  - defaults
dependencies:
  - abseil-cpp
  - aiobotocore
  - aiofiles
  - aiohttp
  - aioitertools
  - aiosignal
  - aiosqlite
  - alabaster
  - anaconda
  - anyio
  - aom
  - appdirs
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - arrow-cpp
  - astroid
  - astropy
  - asttokens
  - async-timeout
  - atomicwrites
  - attrs
  - automat
  - autopep8
  - aws-c-common
  - aws-c-event-stream
  - aws-checksums
  - aws-sdk-cpp
  - babel
  - backcall
  - bcrypt
  - beautifulsoup4
  - binaryornot
  - black
  - blas
  - bleach
  - blosc
  - bokeh
  - boost-cpp
  - botocore
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - certifi
  - cffi
  - cfitsio
  - chardet
  - charls
  - charset-normalizer
  - click
  - cloudpickle
  - colorama
  - colorcet
  - comm
  - constantly
  - contourpy
  - cookiecutter
  - cryptography
  - cssselect
  - curl
  - cycler
  - cytoolz
  - dask
  - dask-core
  - datasets
  - datashader
  - datashape
  - dav1d
  - debugpy
  - decorator
  - defusedxml
  - diff-match-patch
  - dill
  - distributed
  - docstring-to-markdown
  - docutils
  - entrypoints
  - et_xmlfile
  - executing
  - filelock
  - flake8
  - flask
  - fonttools
  - freetype
  - frozenlist
  - fsspec
  - gensim
  - gflags
  - giflib
  - glib
  - glog
  - greenlet
  - grpc-cpp
  - h5py
  - hdf5
  - heapdict
  - holoviews
  - huggingface_hub
  - hvplot
  - hyperlink
  - icu
  - idna
  - imagecodecs
  - imageio
  - imagesize
  - imbalanced-learn
  - importlib-metadata
  - importlib_metadata
  - incremental
  - inflection
  - iniconfig
  - intake
  - intervaltree
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - itemadapter
  - itemloaders
  - itsdangerous
  - jaraco.classes
  - jedi
  - jellyfish
  - jinja2
  - jinja2-time
  - jmespath
  - joblib
  - jpeg
  - jq
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_fileid
  - jupyter_server_ydoc
  - jupyter_ydoc
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kaleido-core
  - keyring
  - kiwisolver
  - krb5
  - lazy-object-proxy
  - lazy_loader
  - lcms2
  - lerc
  - libaec
  - libavif
  - libboost
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libcurl
  - libdeflate
  - libevent
  - libffi
  - libiconv
  - libpng
  - libpq
  - libprotobuf
  - libsodium
  - libspatialindex
  - libssh2
  - libthrift
  - libtiff
  - libwebp
  - libwebp-base
  - libxml2
  - libxslt
  - libzopfli
  - linkify-it-py
  - llvmlite
  - locket
  - lxml
  - lz4
  - lz4-c
  - lzo
  - markdown
  - markdown-it-py
  - markupsafe
  - mathjax
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mccabe
  - mdit-py-plugins
  - mdurl
  - menuinst
  - mistune
  - more-itertools
  - mpmath
  - msgpack-python
  - multidict
  - multipledispatch
  - multiprocess
  - munkres
  - mypy_extensions
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx
  - nltk
  - notebook
  - notebook-shim
  - numba
  - numexpr
  - numpy
  - numpy-base
  - numpydoc
  - openjpeg
  - openpyxl
  - openssl
  - orc
  - packaging
  - pandas
  - pandocfilters
  - panel
  - param
  - paramiko
  - parsel
  - parso
  - partd
  - pathspec
  - patsy
  - pcre
  - pep8
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - plotly
  - pluggy
  - ply
  - poyo
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - protego
  - psutil
  - ptyprocess
  - pure_eval
  - py-cpuinfo
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pycodestyle
  - pycparser
  - pyct
  - pycurl
  - pydispatcher
  - pydocstyle
  - pyerfa
  - pyflakes
  - pygments
  - pylint
  - pylint-venv
  - pyls-spyder
  - pynacl
  - pyodbc
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pyqtwebengine
  - pyrsistent
  - pysocks
  - pytables
  - pytest
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-kaleido
  - python-lmdb
  - python-lsp-black
  - python-lsp-jsonrpc
  - python-lsp-server
  - python-slugify
  - python-snappy
  - python-tzdata
  - python-xxhash
  - pytoolconfig
  - pytz
  - pyviz_comms
  - pywavelets
  - pyyaml
  - pyzmq
  - qdarkstyle
  - qstylizer
  - qt-main
  - qt-webengine
  - qtawesome
  - qtconsole
  - qtpy
  - qtwebkit
  - queuelib
  - re2
  - regex
  - requests
  - requests-file
  - responses
  - rfc3339-validator
  - rfc3986-validator
  - rope
  - rtree
  - s3fs
  - safetensors
  - scikit-image
  - scikit-learn
  - scipy
  - scrapy
  - seaborn
  - send2trash
  - service_identity
  - setuptools
  - sip
  - six
  - smart_open
  - snappy
  - sniffio
  - snowballstemmer
  - sortedcontainers
  - soupsieve
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - spyder
  - spyder-kernels
  - sqlalchemy
  - sqlite
  - stack_data
  - statsmodels
  - sympy
  - tabulate
  - tbb
  - tbb4py
  - tblib
  - tenacity
  - terminado
  - text-unidecode
  - textdistance
  - threadpoolctl
  - three-merge
  - tifffile
  - tinycss2
  - tk
  - tldextract
  - tokenizers
  - toml
  - tomlkit
  - toolz
  - tornado
  - tqdm
  - traitlets
  - transformers
  - twisted
  - typing-extensions
  - typing_extensions
  - tzdata
  - uc-micro-py
  - ujson
  - unidecode
  - urllib3
  - utf8proc
  - w3lib
  - watchdog
  - wcwidth
  - webencodings
  - websocket-client
  - werkzeug
  - whatthepatch
  - wheel
  - widgetsnbextension
  - wrapt
  - xarray
  - xxhash
  - xyzservices
  - xz
  - y-py
  - yaml
  - yapf
  - yarl
  - ypy-websocket
  - zeromq
  - zfp
  - zict
  - zipp
  - zlib
  - zlib-ng
  - zope
  - zope.interface
  - zstd
